---
name: "FolderPlaylist"
guid: "c0046ae9-e598-4f27-ac70-e3337350fa8d"
version: "0.1.0.0"
targetAbi: "10.8.4.0"
framework: "net6.0"
overview: "Create music playlists based on top level folders"
description: >
  Create music playlists based on top level folders
category: "General"
owner: "TheCakeIsNaOH"
artifacts:
- "Jellyfin.Plugin.FolderPlaylist.dll"
changelog: >
  changelog
